### ISSUE TITLE
Question: how does it work?

### ISSUE THREAD

**Issue by VulcanWM** [Dheirya/MeloVybs-Bot#1]
This projects looks amazing!
just wondering how it works and how you made it.

**Comment by Dheirya** [comment]
Hey! Thanks for checking it out!

For how it works, it's not too complicated. The main code is [main.py](https://github.com/Dheirya/MeloVybs-Bot/blob/main/main.py), and it's split into different functions for different tasks, but the basic overview of what it does is:
1. First, the bot picks the first line from assets/songs.txt and downloads the youtube video. The youtube video is usually a song/piano tutorial video
2. Then, I use this pretrained-AI model from ByteDance called [PianoTranscription](https://github.com/bytedance/piano_transcription) to convert the song (mp3) into a bunch of piano notes (midi). 
3. Now that we have the piano notes, we can create the video. I use this library called [synthviz](https://github.com/jxmorris12/synthviz), which takes in a midi file and outputs a mp4 file that is the video.
4. From there, there's not much left to do. I created this thumbnail function which just creates a thumbnail using [pillow](https://pypi.org/project/Pillow/), and then I just upload it onto YouTube. Simple as that.

That's how the project works. As for running it everyday, on my mac, I created a launchctl daemon to run this program every day at 3:00, and that's basically how it works! If you have any questions feel free to ask!

_(Also on a side note, if you have any time, I would really appreciate it if you checked out my [Repl](https://replit.com/@dheiryat/RumbleChat-2-Back-and-Better-Than-Ever?v=1) for RumbleChat and maybe left a like if you wanted to, no worries though!)_

**Comment by VulcanWM** [comment]
wow, that much more sense. thanks for replying so fast!
i checked out rumblechat a while back and the first thing that came to my head was it looks like a professional site lmao.
you definitely have skill!
